import type { NextPage } from "next";

import {
  Wayfinder,
  Card,
  Underlay,
  Jumbotron,
  FooterBase,
  Navbar,
  Skills,
  AboutUs,
  Map,
  Array,
  Patners,
  Testimonials,
} from "../parts";
import Head from "next/head";
import Link from "next/link";
import React, { useState, useEffect } from "react";
import { useSelector } from "react-redux";
import { selectMapIsOpen } from "../store/slices/mapSlice";

const Home: NextPage = () => {
  const mapIsOpen = useSelector(selectMapIsOpen);

  return (
    <div>
      <Head>
        <title>PeerWork</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar />
      <Skills />

      <AboutUs />

      <Patners />

      <div className="">
        <Testimonials />
      </div>

      <div className="py-0 mt-1">
        <div className="h-[2.0px] w-full bg-slate-300 my-2" />
      </div>

      {/* {mapIsOpen && (
        <div className="flex flex-row w-screen h-screen mx-auto mr-20 mx-20 mb-0 mt-5 p-20 ">
          <div className="flex-1 w-64 bg-gray-200">
            <Map />
          </div>
          <div className="flex-1 w-32">
            <Array />
          </div>
        </div>
      )} */}

      <div className="py-0 mt-0">
        <div className="h-[2.0px] w-full bg-slate-300 my-2" />
      </div>

      <div className="flex flex-auto cursor-pointer p-5 m-5 overflow-x-scroll space-x-5">
        {[
          {
            node: "Earth",
            title: "Fill a name",
            location: "M",
            color: "white",
            Img: "/cowork.jpeg",
          },
          {
            node: "Earth",
            title: "Fill a name",
            location: "M",
            color: "white",
            Img: "/cowork.jpeg",
          },
          {
            node: "Earth",
            title: "Fill a name",
            location: "M",
            color: "white",
            Img: "/cowork.jpeg",
          },
        ].map((item) => (
          <Card
            node={item.node}
            title={item.title}
            location={item.location}
            color={item.color}
            Img={item.Img}
          />
        ))}
      </div>

      <Underlay
        u={"Docs"}
        v={"Members"}
        w={"Rentals"}
        x={"Workspaces"}
        y={"Residence"}
        z={"Blog"}
      />
      <Jumbotron />
      <Wayfinder a={"About us"} b={"Services"} c={"Nodes"} d={"Complaints"} />

      <FooterBase />
    </div>
  );
};

export default Home;
